### ISSUE TITLE
user 객체로 중복제거체크

### ISSUE THREAD

**Issue by woo0doo** [Akatsuki-USW/Buzzzzing-Server#56]
![image](https://github.com/Akatsuki-USW/Buzzzzing-Server/assets/114072164/31fdc4ed-f54c-424c-ab73-14516d288813)
현재는 userid로 중복을 제거하고 또다시 userid로 user를 조회하는데 user로 중복을 제거하고 다시 db를 조회하는 과정을 삭제하고싶다.

추후 리펙토링예정

**Comment by wonslee** [comment]
오호 좋아요 :+1:
