### ISSUE TITLE
ControllerAdvice HTTP code 설정

### ISSUE THREAD

**Issue by wonslee** [Akatsuki-USW/Buzzzzing-Server#59]
그동안 ApiResponse가 만능인줄 알았으나, HTTP code까지는 설정할 수 없었다.
따로 설정해주는게 좋다.

![image](https://github.com/Akatsuki-USW/Buzzzzing-Server/assets/72124326/5d459967-71b6-4c77-af01-b37262462be1)

**Comment by woo0doo** [comment]
이해는 잘 안갔지만 이미 하고있지 않나요?

**Comment by wonslee** [comment]
저희는 커스텀 status code만 설정해주고있고, 
HTTP code(200, 404, ...)는 아마 스프링에서 알아서 해주는중입니다ㅋㅋ

**Comment by woo0doo** [comment]
![image](https://github.com/Akatsuki-USW/Buzzzzing-Server/assets/114072164/9478fe06-8def-495e-aade-b197ca65a18b)
여기서 다 잡아주고 있지 않나요?

**Comment by wonslee** [comment]
오옷! 그렇네요?
그 밑의 나머지 핸들러들에서도 잡아주면 되겠네요

**Comment by wonslee** [comment]
자세히 볼 수록 아름답다.
복쟉복쟉도 그렇다.
