### ISSUE TITLE
실서비스 배포와 master 브랜치

### ISSUE THREAD

**Issue by wonslee** [Akatsuki-USW/Buzzzzing-Server#68]
슬슬 master 브랜치로 병합이 필요해보입니다!

현재 CICD는 develop 브랜치에 push (merge) 되었을 때 바로 배포가 되지만, 
앞으로는 master 브랜치만 트리거로 두려구요

즉
평소 개발은 profile : local (로컬 DB를 사용하는 application-local.yml )
배포는 profile : prod (실제 DB를 사용하는 application-prod.yml)

application-dev.yml은 당분간 안 쓰일듯 합니다
서버도 따로 띄우고 싶지만... ec2 멈출까봐 당분간은 못합니다. DB도 따로 띄우는 의미는 크게 없을거같아요

아래 할 일들은 실서비스 배포 시점부터 필수입니다 

### 할 일
- [x] application-local.yml, application-dev.yml  : 로컬 DB로 변경 :exclamation: 
- [x] master 브랜치 병합한 후 release 1.0.0 태그 붙이기 (이유 : 멋)

@wonslee 
- [x] develop : 실서비스에 배포되지 않도록 CICD 파일 변경, application-prod.yml 파일 환경변수 추가. (profile명 : prod)
- [x] develop : logback 추가
- [x] develop : Dummy 파일들 `@Profile` local만 적용

### Version 규칙
![version_rule](https://github.com/Akatsuki-USW/Buzzzzing-Server/assets/72124326/75e9b0dc-2569-49c1-98a9-f28e72249fb3)

> 모든 버전은 1.0.0에서 시작합니다.

- 기존 버전과 호환되지 않는 API 변경 사항 :  **Major Version**를 올립니다.
- 기존 버전과 호환되면서 새로운 기능을 추가 : **Minor Version**를 올립니다.
- 자잘한 버그나 내부적 코드 보완 등의 변화가 발생 :  **Patches**를 올립니다.

참고 : https://blog.naver.com/dilrong/221475400415 https://semver.org/

**Comment by woo0doo** [comment]
👍 배포 드가자~
