### ISSUE TITLE
cors 설정

### ISSUE THREAD

**Issue by woo0doo** [Akatsuki-USW/Buzzzzing-Server#88]
우리가 지정한 프론트만 허용한다?

- SecurityConfig
ex) configuration.setAllowedOrigins(Arrays.asList("https://bokjak.app"));

---
관련 문서
https://dev-pengun.tistory.com/entry/Spring-Boot-CORS-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0
https://velog.io/@soyeon207/%EC%8B%A4%EC%8A%B5%ED%8E%B8-CORS-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0

**Comment by wonslee** [comment]
오 레퍼런스랑 문법이 조금씩 다르긴 한데 맞는것 같습니다
너무 좋아요! :rocket:

**Comment by woo0doo** [comment]
앱은 cors가 없다.. 메..모..
